### ISSUE TITLE
IndexOutOfBoundsException when using back button

### ISSUE THREAD

**Issue by rzimmer** [tvbarthel/IntentShare#46]
Hey there,

first thanks for creating this libary! Sharing is by far not that easy on Android as it should, so _IntentShare_ comes in very handy.

Now to my issue: Selecting an app to share to from the `TargetChooserActivity` works as expected. But going back to my app using Android's back button or application switcher causes a crash of my app with the following stacktrace:

`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:2).state:2
                                                                                at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5427)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                                                                                at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                                                                                at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)
                                                                                at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                                                                                at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:585)
                                                                                at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3457)
                                                                                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3252)
                                                                                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                at android.widget.ScrollView.onLayout(ScrollView.java:1528)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                                at android.view.View.layout(View.java:16646)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
                                                                            	at android.view.ViewRootImpl.performTraver`

For me it seems that the `RecyclerView` in `TargetChooserActivity` is causing the issue as I don't have one in my layout of my activity.

Looking forward to a fix - keep up the good work!

**Comment by tbarthel-fr** [comment]
Hi @rzimmer  (=

First of all thanks for your interest in this project (:

The best scenario for us to solve this issue would be to be able to reproduce it with the sample app so that we can find the source of the concern. 

Unfortunatelly, on our side, pressing back from the ```TargetChooserActivity``` does't lead to any crash.

Could you give us more information on the IntentShare configuration you are using?

I guess you are using the ```v0.0.4```, but are you using glide/picasso loader? Does it happen every time on every phones?

Sorry for these questions but since the stacktrace only reference android framework, any additionnal information would be much appreciate here (=

**Comment by rzimmer** [comment]
You're right in asking these questions. I'm sorry for not giving you more details at the beginning. Digging more into the issue I saw that _my_ code was causing the problem (I overlooked that I used a `RecyclerView` as `ViewPager` replacement).
I'll close this issue now, sorry for reporting a false positive!

**Comment by tbarthel-fr** [comment]
Hi @rzimmer (=

No worries, happy to read that you solve your issue (:

Feel free to make any feedback on the usage of this project. So far it matched our own needs but we don't know yet how other dev integrated it.

Have a good day (=
